@pushOnce('styles')
    <style>
        .twp-root{--twp-primary:#0f766e;--twp-primary-soft:#ccfbf1;--twp-bg:#eef2f3;--twp-surface:#fff;--twp-elevated:#f8fafc;--twp-timeline:#f1f5f9;--twp-line:#dbe3e6;--twp-text:#17252b;--twp-muted:#64747b;--twp-warning:#a16207;--twp-warning-bg:#fef9c3;--twp-error:#b91c1c;--twp-incoming:#fff;--twp-outgoing:#0f766e;color:var(--twp-text);font-size:14px}
        .dark .twp-root{--twp-primary:#2dd4bf;--twp-primary-soft:#123d3a;--twp-bg:#111827;--twp-surface:#18232c;--twp-elevated:#202d36;--twp-timeline:#151f27;--twp-line:#33434c;--twp-text:#edf3f5;--twp-muted:#b2c0c6;--twp-warning:#fde68a;--twp-warning-bg:#493b16;--twp-error:#fecaca;--twp-incoming:#202d36;--twp-outgoing:#0f766e}
        .twp-root.is-r1k{--twp-primary:var(--brand-color);--twp-primary-soft:color-mix(in srgb,var(--brand-color) 9%,#fff);--twp-bg:#f3f4f6;--twp-surface:#fff;--twp-elevated:#f9fafb;--twp-timeline:#f4f6f8;--twp-line:#d1d5db;--twp-text:#1f2937;--twp-muted:#6b7280;--twp-warning:#92400e;--twp-warning-bg:#fffbeb;--twp-incoming:#fff;--twp-outgoing:color-mix(in srgb,var(--brand-color) 86%,#1e3a5f)}
        .dark .twp-root.is-r1k{--twp-primary:var(--brand-color);--twp-primary-soft:color-mix(in srgb,var(--brand-color) 18%,#182230);--twp-bg:#111827;--twp-surface:#182230;--twp-elevated:#202b3a;--twp-timeline:#151f2d;--twp-line:#374151;--twp-text:#f3f4f6;--twp-muted:#c0cad7;--twp-warning:#fcd34d;--twp-warning-bg:#3b3018;--twp-incoming:#202b3a;--twp-outgoing:color-mix(in srgb,var(--brand-color) 66%,#1e293b)}
        .twp-root *,.twp-root *::before,.twp-root *::after{box-sizing:border-box}.twp-root button:focus-visible,.twp-root a:focus-visible,.twp-root input:focus-visible,.twp-root textarea:focus-visible,.twp-root select:focus-visible{outline:3px solid color-mix(in srgb,var(--twp-primary) 55%,transparent);outline-offset:2px}
        .twp-shell{background:var(--twp-bg);border:1px solid var(--twp-line);border-radius:8px;display:grid;grid-template-columns:286px minmax(480px,1fr) 310px;height:calc(100dvh - 130px);min-height:560px;overflow:hidden}.twp-queue,.twp-conversation,.twp-context{background:var(--twp-surface);min-height:0;min-width:0}.twp-queue,.twp-conversation{display:flex;flex-direction:column}.twp-conversation{border-left:1px solid var(--twp-line);position:relative}.twp-context{border-left:1px solid var(--twp-line);overflow-y:auto;padding:18px}.twp-context>aside{display:grid;gap:16px}.twp-context>aside>section{background:transparent;border:0;border-bottom:1px solid var(--twp-line);border-radius:0;padding:0 0 16px}.twp-context>aside>section:last-child{border-bottom:0}
        .twp-queue-head{border-bottom:1px solid var(--twp-line);padding:16px 14px 12px}.twp-eyebrow{color:var(--twp-muted);font-size:12px}.twp-title{font-size:20px;font-weight:700;line-height:1.2;margin:4px 0 0}.twp-tabs{display:grid;gap:0 12px;grid-template-columns:repeat(2,minmax(0,1fr));margin-top:12px}.twp-tab{border-bottom:2px solid transparent;color:var(--twp-muted);display:flex;font-size:11px;justify-content:space-between;min-width:0;padding:8px 1px 7px;text-decoration:none}.twp-tab[aria-current=page]{border-bottom-color:var(--twp-primary);color:var(--twp-primary);font-weight:600}.twp-search{display:block;margin-top:10px;position:relative}.twp-search input{background:var(--twp-surface);border:1px solid var(--twp-line);border-radius:4px;color:var(--twp-text);min-height:38px;padding:0 12px 0 38px;width:100%}.twp-search svg{color:var(--twp-muted);left:12px;position:absolute;top:11px}.twp-search [role=listbox]{background:var(--twp-surface);border:1px solid var(--twp-line);border-radius:6px;box-shadow:0 10px 20px rgba(0,0,0,.12);left:0;margin-top:4px;overflow:hidden;position:absolute;right:0;z-index:20}.twp-search [role=listbox].hidden{display:none}
        .twp-list{flex:1;min-height:0;overflow-y:auto}.twp-row{border-bottom:1px solid var(--twp-line);color:inherit;display:block;min-height:82px;padding:12px 14px;text-decoration:none}.twp-row:hover{background:var(--twp-elevated)}.twp-row.is-active{background:var(--twp-primary-soft);box-shadow:inset 2px 0 var(--twp-primary)}.twp-row-top,.twp-row-meta{align-items:center;display:flex;gap:8px}.twp-row-name{flex:1;font-weight:600;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.twp-time,.twp-row-meta{color:var(--twp-muted);font-size:11px}.twp-preview{color:var(--twp-muted);margin:5px 0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.twp-row-meta{justify-content:space-between}.twp-badge{background:var(--twp-primary);border-radius:999px;color:#fff;font-size:11px;font-weight:600;min-width:22px;padding:2px 7px;text-align:center}.twp-action-dot{background:#d97706;border-radius:50%;height:8px;width:8px}.twp-action-dot.is-overdue{background:#dc2626}.twp-claim{margin-top:10px}.twp-queue-empty{color:var(--twp-muted);padding:24px;text-align:center}.twp-pagination{border-top:1px solid var(--twp-line);padding:8px}
        .twp-empty-workspace{align-items:center;color:var(--twp-muted);display:flex;flex:1;justify-content:center;padding:32px;text-align:center}.twp-context-toggle,.twp-context-close{align-items:center;background:transparent;border:1px solid var(--twp-line);border-radius:6px;color:var(--twp-text);cursor:pointer;display:inline-flex;height:44px;justify-content:center;min-width:44px;padding:0 12px}.twp-context-close{display:none}.twp-scrim{background:rgba(31,41,55,.52);border:0;display:none;inset:0;position:fixed;z-index:10002}
        .twp-root #topweb-chat-timeline{background:var(--twp-timeline)}.twp-root .twp-message-bubble{background:var(--twp-incoming);border-color:var(--twp-line);color:var(--twp-text)}.twp-root .twp-message-outgoing .twp-message-bubble{background:var(--twp-outgoing);border-color:transparent;color:#fff}.twp-root .topweb-chat-internal-note{background:var(--twp-warning-bg);border-color:var(--twp-warning);color:var(--twp-text)}
        @media(max-width:1439px){.twp-shell{grid-template-columns:286px minmax(0,1fr)}.twp-context{border:1px solid var(--twp-line);border-radius:8px;box-shadow:0 10px 20px rgba(0,0,0,.16);display:none;height:calc(100dvh - 24px);max-width:340px;padding-top:70px;position:fixed;right:12px;top:12px;width:min(340px,88vw);z-index:10003}.twp-root.is-context-open .twp-context,.twp-root.is-context-open .twp-scrim{display:block}.twp-context-close{display:inline-flex;position:absolute;right:14px;top:14px}}
        @media(min-width:1440px){.twp-context-toggle{display:none}}
        @media(max-width:1023px){.twp-shell{display:block;height:calc(100dvh - 130px);min-height:520px}.twp-queue,.twp-conversation{height:100%}.twp-root.has-conversation .twp-queue{display:none}.twp-root:not(.has-conversation) .twp-conversation{display:none}}
        @media(max-width:767px){.twp-shell{border-left:0;border-radius:0;border-right:0;height:calc(100dvh - 116px);margin:0 -16px}.twp-context{bottom:12px;height:min(78dvh,620px);left:12px;max-width:none;padding-top:58px;right:12px;top:auto;width:calc(100% - 24px)}.twp-root #topweb-chat-timeline{padding:14px 10px}.twp-root #topweb-chat-send-form{gap:8px;padding:10px}.twp-root #topweb-chat-send-form .primary-button{padding-left:12px;padding-right:12px}}
        @media(prefers-reduced-motion:reduce){.twp-root *,.twp-root *::before{scroll-behavior:auto!important;transition:none!important}}
    </style>
@endPushOnce
